apiVersion: apps/v1
kind: Deployment
metadata:
  name: companyservice
  namespace: jobportal
  labels:
    app: companyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: companyservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: companyservice
    spec:
      containers:
        - name: companyservice
          image: 172.29.3.41:5000/companysvc:1.0.0.8
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "300m"
              memory: "500Mi"
          ports:
            - name: company
              containerPort: 9003
          volumeMounts:
            - name: company-images
              mountPath: /app/src/main/resources/images

      volumes:
        - name: company-images
          persistentVolumeClaim:
            claimName: companyservice-images
