apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobseekerservice
  namespace: jobportal
  labels:
    app: jobseekerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobseekerservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jobseekerservice
    spec:
      containers:
        - name: jobseekerservice
          image: 172.29.3.41:5000/jobseekersvc:1.0.0.7
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "300m"
              memory: "500Mi"
          ports:
            - name: jobseeker
              containerPort: 8085
          volumeMounts:
            - name: jobseeker-images
              mountPath: /app/src/main/resources/images

      volumes:
        - name: jobseeker-images
          persistentVolumeClaim:
            claimName: jobseekerservice-images
